<?php 
	include('phpqrcode/qrlib.php');

	$fullInfo = $_GET['fullInfo'];
	//same as above but outputs file directly into browser (with appr. header etc.)
	//all other settings are default
	//WARNING! it should be FIRST and ONLY output generated by script, otherwise
	//rest of output will land inside PNG binary, breaking it for sure
	QRcode::png($fullInfo);
?>